[supervisord]
nodaemon=true
logfile=/home/container/logs/supervisord.log
logfile_maxbytes=10MB
logfile_backups=5
pidfile=/home/container/tmp/supervisord.pid
childlogdir=/home/container/logs

[program:php-fpm]
command=/usr/local/bin/php-fpm-runtime --nodaemonize --fpm-config /opt/andline/php/php-fpm.conf
priority=10
autostart=true
autorestart=true
startsecs=2
stopasgroup=true
killasgroup=true
stdout_logfile=/home/container/logs/php/fpm-stdout.log
stderr_logfile=/home/container/logs/php/fpm-stderr.log
stdout_logfile_maxbytes=20MB
stderr_logfile_maxbytes=20MB
stdout_logfile_backups=5
stderr_logfile_backups=5

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;" -c /opt/andline/nginx/nginx.conf
priority=20
autostart=true
autorestart=true
startsecs=2
stopasgroup=true
killasgroup=true
stdout_logfile=/home/container/logs/nginx/stdout.log
stderr_logfile=/home/container/logs/nginx/stderr.log
stdout_logfile_maxbytes=20MB
stderr_logfile_maxbytes=20MB
stdout_logfile_backups=5
stderr_logfile_backups=5


[program:newt]
command=/usr/local/bin/andline-newt
priority=25
autostart=true
autorestart=unexpected
startsecs=3
startretries=10
stopasgroup=true
killasgroup=true
stdout_logfile=/home/container/logs/newt/newt.log
stderr_logfile=/home/container/logs/newt/newt-error.log
stdout_logfile_maxbytes=20MB
stderr_logfile_maxbytes=20MB
stdout_logfile_backups=7
stderr_logfile_backups=7

[program:websocket]
command=/usr/local/bin/andline-websocket
priority=30
autostart=true
autorestart=unexpected
startsecs=3
startretries=10
stopasgroup=true
killasgroup=true
stdout_logfile=/home/container/logs/node/websocket.log
stderr_logfile=/home/container/logs/node/websocket-error.log
stdout_logfile_maxbytes=50MB
stderr_logfile_maxbytes=50MB
stdout_logfile_backups=7
stderr_logfile_backups=7

[program:laravel-queue]
command=/usr/local/bin/andline-queue
priority=40
autostart=true
autorestart=unexpected
startsecs=3
startretries=10
stopasgroup=true
killasgroup=true
stdout_logfile=/home/container/logs/laravel/queue.log
stderr_logfile=/home/container/logs/laravel/queue-error.log
stdout_logfile_maxbytes=50MB
stderr_logfile_maxbytes=50MB
stdout_logfile_backups=7
stderr_logfile_backups=7

[program:laravel-scheduler]
command=/usr/local/bin/andline-scheduler
priority=50
autostart=true
autorestart=unexpected
startsecs=3
startretries=10
stopasgroup=true
killasgroup=true
stdout_logfile=/home/container/logs/laravel/scheduler.log
stderr_logfile=/home/container/logs/laravel/scheduler-error.log
stdout_logfile_maxbytes=20MB
stderr_logfile_maxbytes=20MB
stdout_logfile_backups=7
stderr_logfile_backups=7
